#!/usr/bin/env guile \
-e main -s 
!#
(use-modules (experiment)
             (oop goops)
             (experiment-transition))

(define (main args)
  (let ((argc (length args))
        (exp #f)
        (exps #f))
    (when (= 1 argc)
      (format #t "Usage: ~a <filename ...>~%" (car args))
      (exit 2))
    
    (set! exps (map read-experiment (cdr args)))

    (set! exp (make <experiment-transition-parent>
              #:child-experiments
              exps))

    (export-data exp (current-output-port))))
