#!/bin/bash

#eracs -s run-individual -s '#(1 0 0 1)' -o results-12.m -r '(.1 .3 .5 1. 2.)' results-12/f2b2-1.dat

#eracs -s run-individual -s '#(-.1 .1 -.1 -.1)' -o results-12-hand.m -r '(.1 .3 .5 1. 2.)' results-12/f2b2-1.dat

#eracs -s run-individual -s '#(1 0 0 1)' -o results-13.m -r '(.1 .3 .5 1. 2.)' results-13/f2b2-2.dat

eracs -s run-individual -s '#(-.1 0 0 0)' -o results-13-hand.m -r '(.1 .3 .5 1. 2.)' results-13/f2b2-2.dat
