#!/usr/bin/env guile \
--debug -e main -s 
!#
(use-modules (experiment))

(define (main args)
  (let ((argc (length args))
        (filename #f)
        (exp #f))
    (unless (= 2 argc)
      (format #t "Usage: redo-analyze <filename>~%")
      (exit 2))
    (set! filename (cadr args))

    (set! exp (read-experiment filename))

    (format #t "analyze-data! ~a~%" (analyze-data! exp))))
